minimum_pre_commit_version: 3.2.0
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.81.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
    args:
    - '--args=--sort-by required'
  - id: terraform_validate
  - id: terraform_tflint
    args:
    - '--args=--only=terraform_deprecated_interpolation'
    - '--args=--only=terraform_deprecated_index'
    - '--args=--only=terraform_unused_declarations'
    - '--args=--only=terraform_comment_syntax'
    - '--args=--only=terraform_documented_outputs'
    - '--args=--only=terraform_documented_variables'
    - '--args=--only=terraform_typed_variables'
    #- '--args=--only=terraform_module_pinned_source'
    - '--args=--only=terraform_naming_convention'
    - '--args=--only=terraform_required_version'
    - '--args=--only=terraform_required_providers'
    - '--args=--only=terraform_standard_module_structure'
  - id: terraform_tfsec
    stages: [pre-commit, post-commit]
    args:
    - >
      --args=
        --soft-fail
        --single-thread
        --exclude-downloaded-modules
        --format markdown
        --out TFSec-result.md